Move or sync profiles and verification scripts
yast/aytests-tests pull request #95
Opened 2017-07-28 14:45 UTC by rwx788

As part of improvement of autoyast tests, we want to keep profiles and
verification scripts in single place. As same profiles are used for
integration tests, we move them to aytests repository.
Whereas, as some files were forked, we need to sync them, to be on the
same side. After merging these changes, settings of relevant jobs have
to be changed. There will be another merge required for
os-autoinst-distri-opensuse repository.

@schubi2 please review if there is any issues to run these in your setup.
ftp profile mainly has changes in formatting, and only 2 settings were changes.
For lvm, somehow openQA is not capable of other layouts than default and for example instead of ";" we print a umlaut.

Changes to openQA distri repo are suggested in [PR#3358](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/3358)

2017-08-01 10:43 UTC, schubi2 requested changes
I am missing the corresponding files *.list *.rb for the new testcases bug-870820 and dns in order to get a connection between the testcases and the checking scripts.

2017-08-01 10:43 UTC, schubi2 commented on aytests/bug-870820.xml
> +          wget ftp://music.arch.suse.de/scripts/after_install.sh
Hm, I fear we will not have connections to music.arch.suse in our test environment

2017-08-01 10:43 UTC, schubi2 commented on aytests/bug-870820.xml
> +          wget ftp://music.arch.suse.de/scripts/after_install.sh
Have a look to:
https://github.com/yast/aytests-tests/blob/master/aytests/tftp.vars
Perhaps we can use ENV variables instead.

2017-08-01 10:43 UTC, schubi2 commented on aytests/ftp.xml
> -    <x config:type="boolean">false</x>
Good point. That is really not needed.

2017-08-01 10:43 UTC, schubi2 commented on aytests/lvm.xml
> -  <language>
That is still needed for test keyboard.sh

2017-08-01 15:56 UTC, rwx788 commented on aytests/bug-870820.xml
> +          wget ftp://music.arch.suse.de/scripts/after_install.sh
Seems that part was used for some env configuration. I've tested it with openQA and it works fine: http://gershwin.arch.suse.de/tests/1233, so I've simply removed this part.

2017-08-01 15:57 UTC, rwx788 commented on aytests/lvm.xml
> -  <language>
As per our discussion, I've moved this check to lvm_auto.list test, where we also set German as system language.

2017-08-14 12:24 UTC, schubi2 approved these changes
LGTM. Let's try it. :-)

2017-08-14 13:50 UTC, merged